version: '3'
services:
docker-app:
   image: calcardev/calcardev
   ports:
     - "8080:8080"
   depends_on:
     - docker-postgres
docker-postgres:
   image: postgres:9.5
   environment:
     - POSTGRES_DB=calcard
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=1234